name: Setup
inputs:
  buildbuddy_api_key:
    required: true
runs:
  using: composite
  steps:
    - name: Set Env
      shell: bash
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/.android/sdk" >> "$GITHUB_ENV"
        echo "ANDROID_HOME=$HOME/.android/sdk" >> "$GITHUB_ENV"
        echo "ANDROID_NDK_HOME=$HOME/.android/sdk/ndk/26.3.11579264" >> "$GITHUB_ENV"
    - uses: bazel-contrib/setup-bazel@0.8.4
      with:
        bazelisk-version: "1.20.0"
        bazelisk-cache: true
        disk-cache: true
        external-cache: true
        repository-cache: true
        bazelrc: |
          common --remote_header=x-buildbuddy-api-key=${{ inputs.buildbuddy_api_key }}
    - name: Mount android cache
      uses: actions/cache@v4
      with:
        path: "~/.android"
        key: android
    - uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: "21"
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        log-accepted-android-sdk-licenses: "false"
        packages: "build-tools;34.0.0 ndk;26.3.11579264 platform-tools platforms;android-34 tools"
    - run: ls $HOME/.android/sdk
      shell: bash
