[workspace]
members = ["qrcloak-core", "qrcodegen"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.0.1"


[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
