[workspace]
members = ["qrypt-core", "qrypt-uniffi", "qrypt-wasm"]
resolver = "2"

[workspace.package]
version = "0.0.1"

[workspace.dependencies]
qrypt-core = { path = "./qrypt-core" }
qrypt-uniffi = { path = "./qrypt-uniffi" }
qrypt-wasm = { path = "./qrypt-wasm" }
