[package]
name = "qrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.12"

[build-dependencies]
prost-build = { version = "0.12" }
protox = { version = "0.6" }
miette = { version = "7.0.0", features = [ "fancy" ] }

[dev-dependencies]
insta = { version = "1.34.0", features = ["yaml"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3