#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 Felix Hilgers <contact@fhilgers.com>
#
# SPDX-License-Identifier: CC0-1.0

parent_path=$(
	cd "$(dirname "${BASH_SOURCE[0]}")"
	pwd -P
)

find $parent_path/deps -name "*.jar" -printf "%p:" | sed 's/:$//'
echo
