# SPDX-FileCopyrightText: 2024 Felix Hilgers <copyright@relay.fhilgers.com>
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
SPDX-FileCopyrightText = "Felix Hilgers <copyright@relay.fhilgers.com>"
SPDX-License-Identifier = "CC0-1.0"
path = [
  ".bazelversion",
  ".github/**",
  "MODULE.bazel.lock",
  "flake.lock",
  "manifest_install.json",
  "qrcloak/Cargo.lock",
  "qrcloak/qrcloak-core/src/format/snapshots/qrcloak_core__format__tests__validate_schema.snap",
  "rust-toolchain",
  "tools/requirements.txt",
]
precedence = "override"

[[annotations]]
SPDX-FileCopyrightText = "The Android Open Source Project"
SPDX-License-Identifier = "Apache-2.0"
path = [
  "qrcloak/qrcloak-android/app/proguard-rules.pro",
  "qrcloak/qrcloak-android/app/src/main/res/**",
]
