[package]
edition.workspace = true
name = "wasm-bindgen-brand"
version.workspace = true

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.81"
quote = "1.0.36"
syn = "2.0.60"
