wasm:
  #!/usr/bin/env sh
  cargo build --package=qrcloak-bindings --release --target=wasm32-unknown-unknown

  wasm-bindgen --target nodejs --out-dir languages/qrcloak-js/pkg/nodejs ../target/wasm32-unknown-unknown/release/qrcloak_bindings.wasm
  wasm-bindgen --target bundler --out-dir languages/qrcloak-js/pkg/bundler ../target/wasm32-unknown-unknown/release/qrcloak_bindings.wasm

  wasm-opt languages/qrcloak-js/pkg/nodejs/qrcloak_bindings_bg.wasm -o languages/qrcloak-js/pkg/nodejs/qrcloak_bindings_bg.wasm -Oz
  wasm-opt languages/qrcloak-js/pkg/bundler/qrcloak_bindings_bg.wasm -o languages/qrcloak-js/pkg/bundler/qrcloak_bindings_bg.wasm -Oz

  echo -n "*" > languages/qrcloak-js/pkg/.gitignore

test-js: wasm
  #!/usr/bin/env sh
  cd ./languages/qrcloak-js
  bun test

publish-js: wasm test-js
  #!/usr/bin/env sh
  cd ./languages/qrcloak-js
  npm publish
  