[package]
edition.workspace = true
name = "qrcodegen"
version.workspace = true

[dev-dependencies]
image = "0.25.1"
proptest = "1.4.0"
proptest-derive = "0.4.0"
quickcheck = "1.0.3"
quircs = "0.10.2"
